### ISSUE TITLE
Not getting the correct Text Tap in a UITableViewCell

### ISSUE THREAD

**Issue by solejay** [evilBird/HBVLinkedTextView#1]
Hi, I use this component in a UItableView, but for some strange  reason when i scroll the table view up and down and then tapped on a linked string it displays the wrong text tapped.
Still dont understand why this happens

**Comment by solejay** [comment]
This  was not a bug. Solved this by making sure i created a new instance of the HBVLinkedTextView in every Cell

**Comment by evilBird** [comment]
Just saw this, thanks for reporting and thanks for posting your fix!

**Comment by evilBird** [comment]
Also curious--did you try calling the 'reset' method?

**Comment by solejay** [comment]
Nope I didn't. What i realised was the instance of the textview was pointing to a existing reference which cause the linkedTextRangeDictionary to have a greater size that the number of actual linked string and it also happened that two different keys had the same range location. So i was picking the first key it found which happened to be the wrong one..So a new instance every time on scroll did the trickSent using CloudMagicOn Thu, Oct 16, 2014 at 4:35 PM,  evilBird/HBVLinkedTextView reply@reply.github.com wrote:            Also curious--did you try calling the 'reset' method?

On Thu, Oct 16, 2014 at 10:33 AM, Travis Henspeter <
